gentics/cms-oss

cms-core/src/main/java/com/gentics/contentnode/object/parttype/FileURLPartType.java
cms-core/src/main/java/com/gentics/contentnode/object/parttype/FolderURLPartType.java
cms-core/src/main/java/com/gentics/contentnode/object/parttype/ImageURLPartType.java
cms-core/src/main/java/com/gentics/contentnode/object/parttype/PageURLPartType.java
cms-oss-changelog/src/changelog/entries/2023/07/7459.SUP-15405.bugfix

https://jira.gentics.com/browse/SUP-15405

SUP-15405 Fix gtx_channel rendering

---

cms-core/src/main/java/com/gentics/contentnode/object/ContentFile.java
cms-core/src/main/java/com/gentics/contentnode/object/NodeObjectInFolder.java
cms-core/src/main/java/com/gentics/contentnode/object/Page.java
cms-core/src/main/java/com/gentics/contentnode/object/PublishableNodeObjectInFolder.java
cms-core/src/test/java/com/gentics/contentnode/tests/utils/ContentNodeTestUtils.java
cms-oss-changelog/src/changelog/entries/2023/07/7510.SUP-15541.bugfix
cms-ui/apps/editor-ui/src/app/shared/components/inheritance-dialog/inheritance-dialog.component.html
cms-ui/apps/editor-ui/src/app/shared/components/inheritance-dialog/inheritance-dialog.component.spec.ts
cms-ui/apps/editor-ui/src/app/shared/components/inheritance-dialog/inheritance-dialog.component.ts

* Possible "data inconsistent" errors when checking permissions
* Several Inheritance dialog issues

Fix multiple problems with inheritance:

---

cms-core/src/main/java/com/gentics/contentnode/messaging/Message.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/MessagingResourceImpl.java
cms-core/src/test/java/com/gentics/contentnode/tests/message/MessagingResourceTest.java
cms-restapi/src/main/java/com/gentics/contentnode/rest/model/request/MessageSendRequest.java
cms-restapi/src/main/java/com/gentics/contentnode/rest/model/response/Message.java
cms-ui/.prettierrc
cms-ui/apps/admin-ui/src/app/core/providers/i18n/translations/common.translations.json
cms-ui/apps/admin-ui/src/app/core/providers/message/message.service.ts
cms-ui/apps/admin-ui/src/app/state/messages/message.actions.ts
cms-ui/apps/admin-ui/src/app/state/messages/message.state.ts
cms-ui/apps/editor-ui/src/app/common/models/message-state.ts
cms-ui/apps/editor-ui/src/app/core/providers/i18n/translations/message.translations.yml
cms-ui/apps/editor-ui/src/app/core/providers/message/message.service.ts
cms-ui/apps/editor-ui/src/app/state/modules/messages/message.actions.ts
cms-ui/apps/editor-ui/src/app/state/modules/messages/message.state-module.ts
cms-ui/apps/editor-ui/src/app/state/providers/message-actions/message-actions.service.ts
cms-ui/libs/cms-models/src/lib/models/message.ts

Issue: https://jira.gentics.com/browse/SUP-15450

SUP-15450: Fix instant messaging

---

cms-core/src/main/java/com/gentics/contentnode/publish/mesh/MeshPublisher.java
cms-oss-changelog/src/changelog/entries/2023/08/7543.SUP-15578.bugfix

https://jira.gentics.com/browse/SUP-15578

SUP-15578: Remove superfluous error message when validating Mesh-SQL CRs

---

cms-oss-changelog/src/changelog/entries/2023/09/7558.SUP-15796.documentation
cms-oss-doc/src/main/source/oss-feature_overview.textile
cms-oss-doc/src/main/source/scheduler_api.textile

https://jira.gentics.com/browse/SUP-15796

SUP-15796 Add documentation for custom tasks and INSECURE_SCHEDULER_COMMAND feature

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/ConstructFactory.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/OverviewPartSetting.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/PartFactory.java
cms-oss-changelog/src/changelog/entries/2023/09/7557.SUP-15749.bugfix

devtool packages.
Add debug log.

Fix incorrect change detection when synchronizing constructs from

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/FolderFactory.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/TemplateFactory.java
cms-core/src/main/java/com/gentics/contentnode/object/Template.java
cms-core/src/main/java/com/gentics/contentnode/perm/PermHandler.java
cms-core/src/main/java/com/gentics/contentnode/publish/wrapper/PublishableTemplate.java
cms-oss-changelog/src/changelog/entries/2023/09/7562.SUP-15821.bugfix

Improve permission checks on templates

Store folderIds of folders, to which templates are linked.

---

cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/index.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-language-switcher/mesh-browser-language-switcher.component.html
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-language-switcher/mesh-browser-language-switcher.component.scss
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-language-switcher/mesh-browser-language-switcher.component.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-master/mesh-browser-master.component.html
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-master/mesh-browser-master.component.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-schema-items/mesh-browser-schema-items.component.html
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-schema-items/mesh-browser-schema-items.component.scss
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-schema-items/mesh-browser-schema-items.component.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-schema-list/mesh-browser-schema-list.component.html
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-schema-list/mesh-browser-schema-list.component.scss
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-schema-list/mesh-browser-schema-list.component.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/mesh-browser.module.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/models/mesh-browser-models.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/providers/mesh-browser-loader.service.ts

Issue: https://jira.gentics.com/browse/GPU-1147

GPU-1147 - Language Switcher

---

cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/FolderResourceImpl.java
cms-core/src/main/resources/contentnode_de_DE.properties
cms-core/src/main/resources/contentnode_en_EN.properties
cms-core/src/main/resources/contentnode_fr.properties
cms-core/src/main/resources/contentnode_it.properties
cms-core/src/test/java/com/gentics/contentnode/tests/rest/FolderResourceTest.java
cms-oss-changelog/src/changelog/entries/2023/11/7611.SUP-15965.bugfix
cms-ui/apps/editor-ui/src/app/shared/components/folder-properties-form/folder-properties-form.component.ts

https://jira.gentics.com/browse/SUP-15965

SUP-15965 Add pubdir check when publish dir segments is active

---

cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-editor/mesh-browser-editor.component.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/mesh-browser.module.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/models/mesh-browser-models.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/providers/index.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/providers/mesh-browser-image-service.ts
cms-ui/apps/admin-ui/src/app/features/mesh-browser/providers/mesh-browser-loader.service.ts
cms-ui/libs/mesh-rest-client-angular/src/lib/mesh-rest-client.service.ts
cms-ui/libs/mesh-rest-client/src/lib/client.ts

Ticket: https://jira.gentics.com/browse/GPU-1382

GPU-1382 - Image Display

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/AbstractFactory.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/DisinheritUtils.java
cms-core/src/main/java/com/gentics/contentnode/factory/url/StaticUrlFactory.java
cms-core/src/main/java/com/gentics/contentnode/publish/FilePublisher.java
cms-core/src/main/java/com/gentics/contentnode/publish/PublishtableUpdateJob.java
cms-core/src/test/java/com/gentics/contentnode/tests/feature/niceurl/AbstractNiceURLUniquenessTest.java
cms-core/src/test/java/com/gentics/contentnode/tests/publish/filesystem/FilesystemPublishTest.java
cms-core/src/test/java/com/gentics/contentnode/tests/utils/ContentNodeTestUtils.java
cms-oss-changelog/src/changelog/entries/2023/11/7624.SUP-15727.bugfix
cms-oss-changelog/src/changelog/entries/2023/11/7625.SUP-15727.bugfix

Fix URL uniqueness checks and publish paths for publishing into the

---

cms-ui/apps/admin-ui-e2e/.eslintrc.json
cms-ui/apps/admin-ui-e2e/src/e2e/mesh-browser.cy.ts
cms-ui/apps/admin-ui/src/app/dashboard/components/dashboard/dashboard.component.html
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-schema-items/mesh-browser-schema-items.component.html
cms-ui/apps/editor-ui-e2e/.eslintrc.json
cms-ui/package-lock.json
cms-ui/package.json

Issue: https://jira.gentics.com/secure/RapidBoard.jspa?rapidView=99&view=detail&selectedIssue=GPU-1060&quickFilter=392

GPU-1060 - Mesh Browser Tests

---

cms-core/src/main/java/com/gentics/contentnode/factory/RenderTypeTrx.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/FormFactory.java
cms-core/src/main/java/com/gentics/contentnode/init/MigrateScheduler.java
cms-core/src/main/java/com/gentics/contentnode/publish/mesh/MeshPublisher.java
cms-core/src/main/java/com/gentics/contentnode/render/RenderUtils.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/PageResourceImpl.java
cms-core/src/main/java/com/gentics/contentnode/rest/util/ModelBuilder.java
cms-core/src/test/java/com/gentics/contentnode/tests/config/NodeConfigTest.java
cms-oss-changelog/src/changelog/entries/2023/11/7626.SUP-16085.bugfix

https://jira.gentics.com/browse/SUP-16085

SUP-16085 Fix page online status during instant publish

---

cms-oss-changelog/src/changelog/entries/2023/12/7647.SUP-16079.bugfix
cms-ui/apps/editor-ui/src/app/state/providers/folder-actions/folder-actions.service.ts

https://jira.gentics.com/browse/SUP-16079

SUP-16079: Fix page language indicator - Missing language variants

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/TemplateFactory.java
cms-core/src/main/java/com/gentics/contentnode/perm/PermHandler.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/NodeResourceImpl.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/TemplateResourceImpl.java
cms-oss-changelog/src/changelog/entries/2023/12/7642.SUP-15906.bugfix
cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/NodeResource.java
cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/TemplateResource.java
cms-ui/apps/admin-ui/src/app/core/providers/i18n/translations/template.translations.json
cms-ui/apps/admin-ui/src/app/core/providers/operations/node/node.operations.ts
cms-ui/apps/admin-ui/src/app/core/providers/operations/template/template.operations.ts
cms-ui/apps/admin-ui/src/app/features/template/components/assign-templates-to-nodes-modal/assign-templates-to-nodes-modal.component.ts
cms-ui/libs/cms-rest-clients-angular/src/lib/node/node-api.ts
cms-ui/libs/cms-rest-clients-angular/src/lib/template/template-api.ts

Refactor getting nodes to which templates are linked

Add REST endpoints

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/ConstructFactory.java
cms-core/src/main/java/com/gentics/contentnode/object/Construct.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/ConstructResourceImpl.java
cms-core/src/main/resources/contentnode_de_DE.properties
cms-core/src/main/resources/contentnode_en_EN.properties
cms-core/src/test/java/com/gentics/contentnode/tests/rest/ConstructResourceTest.java
cms-oss-changelog/src/changelog/entries/2023/12/7648.SUP-15453.bugfix
cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/ConstructResource.java

cannot be deleted, because it is still in use

Fix display of error message when construct

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/PageFactory.java
cms-oss-changelog/src/changelog/entries/2023/12/7649.SUP-16187.bugfix

Fix getting the page language in PageFactory.flush() if language is

---

cms-oss-changelog/src/changelog/entries/2024/03/7708.SUP-16408.bugfix
cms-ui/libs/cms-components/src/lib/form-controls/i18n-select/i18n-select.component.html
cms-ui/libs/cms-components/src/lib/form-controls/i18n-select/i18n-select.component.ts
cms-ui/libs/form-generator/src/lib/core/components/form-element-properties-editor/form-element-properties-editor.component.html
cms-ui/libs/form-generator/src/lib/core/components/form-element-properties-editor/form-element-properties-editor.component.scss

Issue: https://jira-gentics.atlassian.net/browse/SUP-16408

SUP-16408 -FORMULAR - ausgewählter Validator soll wieder entfernt werden können [VS]

---

cms-oss-changelog/src/changelog/entries/2024/03/7713.SUP-16211.bugfix
cms-ui/apps/editor-ui/src/app/content-frame/components/form-reports-list/form-reports-list.component.ts

https://jira-gentics.atlassian.net/browse/SUP-16211

SUP-16211: Formular-Einträge lassen sich nicht löschen

---

cms-ui/apps/admin-ui/src/app/core/providers/dev-tool-check-trable-loader/dev-tool-check-trable-loader.service.ts
cms-ui/apps/admin-ui/src/app/core/providers/dev-tool-package-handler/dev-tool-package-handler.service.ts
cms-ui/apps/admin-ui/src/app/core/providers/i18n/translations/package.translations.json
cms-ui/apps/admin-ui/src/app/features/dev-tool-package/components/dev-tool-package-editor/dev-tool-package-editor.component.scss
cms-ui/apps/admin-ui/src/app/features/dev-tool-package/components/dev-tool-package-editor/package-check-wrapper/package-check-wrapper.component.html
cms-ui/apps/admin-ui/src/app/shared/components/dev-tool-package-trable/dev-tool-package-trable.component.html
cms-ui/apps/admin-ui/src/app/shared/components/dev-tool-package-trable/dev-tool-package-trable.component.scss
cms-ui/apps/admin-ui/src/app/shared/components/dev-tool-package-trable/dev-tool-package-trable.component.ts
cms-ui/libs/cms-models/src/lib/models/request.ts

Issue: https://jira-gentics.atlassian.net/browse/GPU-1395

GPU-1395: Filter and/or Highlight Inconsistencies

---

cms-ui/apps/admin-ui/src/app/mesh/components/login-gate/login-gate.component.ts

Issue: https://jira-gentics.atlassian.net/browse/GPU-1443

GPU-1443: Fix LoginGate form is shown while navigating

---

cms-ui/apps/admin-ui/src/app/mesh/components/login-gate/login-gate.component.ts

Issue: https://jira-gentics.atlassian.net/browse/GPU-1474

GPU-1474: Fix login gate 

---

cms-ui/apps/admin-ui/src/app/core/providers/content-repository-handler/content-repository-handler.service.ts
cms-ui/apps/admin-ui/src/app/features/content-repository/components/content-repository-editor/content-repository-editor.component.ts
cms-ui/apps/admin-ui/src/app/features/content-repository/components/create-content-repository-modal/create-content-repository-modal.component.ts

This needs to be done for creation also

Fix normalizing contentrepository before sending it to REST API

---

cms-ui/libs/cms-rest-client/src/lib/client.ts

Issue: https://jira-gentics.atlassian.net/browse/GPU-1483

GPU-1483: Uploading Images does not work anymore

---

cms-ui/apps/admin-ui/src/app/core/providers/object-property-handler/object-property-handler.service.ts

Issue: https://jira-gentics.atlassian.net/browse/GPU-1228

GPU-1228: [Admin-UI] Wrong REST endpoints for object property management

---

cms-ui/libs/ui-core/src/lib/components/tooltip-content-wrapper/tooltip-content-wrapper.component.scss

Issue: https://jira-gentics.atlassian.net/browse/GPU-1497

GPU-1497: Fix Tooltip Visiblility

---

cms-oss-changelog/src/changelog/entries/2024/2024/04/7754.SUP-16609.bugfix
cms-oss-changelog/src/changelog/entries/2024/2024/XXXX.SUP-1496.bugfix
cms-ui/apps/admin-ui/src/app/app.component.html

Issue: https://jira-gentics.atlassian.net/browse/GPU-1496

SUP-16609: Message Icon is not shown

---

cms-oss-changelog/src/changelog/entries/2024/2024/04/7755.SUP-15810.bugfix
cms-ui/libs/form-generator/src/lib/core/components/form-editor-element/form-editor-element.component.scss

Issue: https://jira-gentics.atlassian.net/browse/SUP-15810

SUP-15810: Fix visiblity of select options

---

cms-aloha-plugins/src/main/js/gcn/lib/gcn-links.js

https://jira-gentics.atlassian.net/browse/GPU-1482

GPU-1482 Fix link creation in gcn-link plugin

---

cms-ui/apps/editor-ui/src/app/core/providers/context-menu-operations/context-menu-operations.service.ts
cms-ui/apps/editor-ui/src/app/state/providers/folder-actions/folder-actions.service.ts
cms-ui/libs/cms-rest-client/src/lib/utils.ts

Issues:
- https://jira-gentics.atlassian.net/browse/GPU-1532
- https://jira-gentics.atlassian.net/browse/GPU-1535

GPU-1535: Moving/Copiyng Files Not Possible

---

cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/PackageResourceImpl.java
cms-core/src/main/resources/contentnode_de_DE.properties
cms-core/src/main/resources/contentnode_en_EN.properties
cms-oss-changelog/src/changelog/entries/2024/04/7760.SUP-16632.bugfix
cms-ui/apps/admin-ui/src/app/core/providers/dev-tool-package-table-loader/dev-tool-package-table-loader.service.ts
cms-ui/apps/admin-ui/src/app/core/providers/operations/package/package.operations.ts
cms-ui/apps/admin-ui/src/app/shared/components/dev-tool-package-table/dev-tool-package-table.component.ts

Issue: https://jira-gentics.atlassian.net/browse/SUP-16632

SUP-16632: Fix Channel Package Loading

---

cms-oss-changelog/src/changelog/entries/2024/04/7765.SUP-16648.bugfix
cms-ui/libs/cms-components/src/lib/core/components/versions-modal/versions-modal.component.html

Issue: https://jira-gentics.atlassian.net/browse/SUP-16648

SUP-16648: Fix Modal Button of Sidebar

---

cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/NodeResourceImpl.java
cms-oss-changelog/src/changelog/entries/2024/04/7771.SUP-16646.bugfix
cms-ui/apps/admin-ui/src/app/core/providers/node-table-loader/node-table-loader.service.ts
cms-ui/apps/admin-ui/src/app/features/node/components/node-master/node-master.component.ts

Issue: https://jira-gentics.atlassian.net/browse/SUP-16646

SUP-16646: Copying Channels not implemented, deleting of copies creates DB inconsistencies

---

cms-oss-changelog/src/changelog/entries/2024/04/7777.SUP-15742.bugfix
cms-ui/apps/admin-ui/src/app/core/providers/i18n/translations/shared.translations.json
cms-ui/apps/admin-ui/src/app/core/providers/language-table-loader/language-table-loader.service.ts
cms-ui/apps/admin-ui/src/app/core/providers/operations/language/language.operations.ts
cms-ui/apps/admin-ui/src/app/shared/components/language-table/language-table.component.ts

Issue: https://jira-gentics.atlassian.net/browse/SUP-15742

SUP-15742: CMS Admin UI - Language cannot be deactivated for a Node

---

cms-core/src/main/java/com/gentics/contentnode/factory/AbstractRecalcSortOrderTransactional.java
cms-core/src/main/java/com/gentics/contentnode/factory/RecalcConstructCategorySortOrderTransactional.java
cms-core/src/main/java/com/gentics/contentnode/factory/RecalcObjectTagDefinitionCategorySortOrderTransactional.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/ConstructFactory.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/ObjectTagDefinitionFactory.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/ConstructResourceImpl.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/TemplateResourceImpl.java
cms-core/src/test/java/com/gentics/contentnode/tests/devtools/SortingTest.java
cms-core/src/test/java/com/gentics/contentnode/tests/rest/ConstructResourceTest.java
cms-core/src/test/java/com/gentics/contentnode/tests/rest/construct/ConstructResourceListCategoriesTest.java
cms-oss-changelog/src/changelog/entries/2024/05/7802.SUP-15490.bugfix
cms-oss-changelog/src/changelog/entries/2024/05/7803.SUP-15490.bugfix
cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/ConstructResource.java
cms-ui/apps/admin-ui/src/app/core/providers/construct-category-handler/construct-category-handler.service.ts
cms-ui/apps/admin-ui/src/app/features/construct/components/construct-category-table/construct-category-table.component.ts

Fix deleting construct categories

Keep sort orders of categories consistent

---

cms-core/src/main/java/com/gentics/contentnode/devtools/Synchronizer.java
cms-core/src/main/java/com/gentics/contentnode/factory/object/SchedulerFactory.java
cms-core/src/main/java/com/gentics/contentnode/publish/MultithreadedPagePublisher.java
cms-core/src/main/java/com/gentics/contentnode/publish/PublishQueue.java
cms-core/src/main/java/com/gentics/contentnode/publish/PublishQueueStats.java
cms-core/src/main/java/com/gentics/contentnode/rest/util/Operator.java
cms-core/src/main/java/com/gentics/contentnode/runtime/NodeConfigRuntimeConfiguration.java
cms-core/src/main/java/com/gentics/contentnode/tools/UpdateImplementation.java
cms-core/src/main/java/com/gentics/contentnode/tools/update/Logger.java
cms-oss-changelog/src/changelog/entries/2024/05/7836.SUP-16705.bugfix
cms-oss-changelog/src/changelog/entries/2024/05/7837.SUP-16705.bugfix
cms-oss-changelog/src/changelog/entries/2024/05/7838.SUP-16705.bugfix
cms-oss-changelog/src/changelog/entries/2024/05/7839.SUP-16705.documentation
cms-oss-doc/src/main/source/rest_java_client.textile

Various fixes for stability when using the UpdateImplementation

---

cms-oss-changelog/src/changelog/entries/2024/07/7889.SUP-17007.bugfix
cms-ui/apps/admin-ui/src/app/features/mesh-browser/providers/mesh-browser-loader.service.ts

Issue: https://jira-gentics.atlassian.net/browse/SUP-17007

SUP-17007: Mesh Browser: Fix loading of content nodes

---

cms-oss-changelog/src/changelog/entries/2024/07/7900.SUP-16839.bugfix
cms-ui/apps/admin-ui/src/app/features/object-property/providers/object-property-category-table-loader/object-property-category-table-loader.service.ts
cms-ui/apps/admin-ui/src/app/shared/shared.module.ts

Issue: https://jira-gentics.atlassian.net/jira/software/c/projects/GTX/boards/31?selectedIssue=SUP-16839

SUP-16839: Object-Property- & Construct-Category sorting

---

cms-oss-changelog/src/changelog/entries/2024/07/7901.SUP-17092.bugfix
cms-ui/apps/editor-ui/src/app/list-view/components/item-list-header/item-list-header.component.html
cms-ui/apps/editor-ui/src/app/list-view/components/item-list-header/item-list-header.component.ts
cms-ui/apps/editor-ui/src/app/shared/components/language-context-selector/language-context-selector.component.html
cms-ui/apps/editor-ui/src/app/shared/components/language-context-selector/language-context-selector.component.ts

Issue: https://jira-gentics.atlassian.net/browse/SUP-17092

SUP-17092: Fix language switching

---

.gitignore
cms-oss-changelog/src/changelog/entries/2024/07/7916.SUP-17123.enhancement
cms-ui/apps/editor-ui/src/app/content-frame/components/form-reports-list/form-reports-list.component.ts
cms-ui/apps/editor-ui/src/app/core/providers/i18n/translations/editor.translations.yml

Issue: https://jira-gentics.atlassian.net/browse/SUP-17123

SUP-17123: Improve UX by adding response messages

---

cms-aloha-plugins/src/main/js/spellcheck/lib/spellcheck-plugin.js
cms-core/src/main/resources/com/gentics/contentnode/runtime/config.yml
cms-oss-changelog/src/changelog/entries/2024/08/7928.SUP-15430.bugfix
cms-ui/proxy.conf.json.example

Issue: https://jira-gentics.atlassian.net/browse/SUP-15430

SUP-15430: Fix spellchecker

---

cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/UserResourceImpl.java
cms-oss-changelog/src/changelog/entries/2024/09/7953.SUP-17263.bugfix

https://jira-gentics.atlassian.net/browse/SUP-17263

SUP-17263 Fix misleading error message when adding users to groups

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/TagFactory.java
cms-core/src/main/java/com/gentics/contentnode/object/ObjectTag.java
cms-core/src/main/java/com/gentics/contentnode/perm/PermHandler.java
cms-core/src/main/java/com/gentics/contentnode/publish/wrapper/PublishableObjectTag.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/ObjTagDefinitionResourceImpl.java
cms-core/src/test/java/com/gentics/contentnode/tests/rest/ObjTagSyncWastebinTest.java
cms-oss-changelog/src/changelog/entries/2024/09/7967.SUP-17442.bugfix

Fix checking permissions on object tags to not consider synchronized

---

cms-core/src/main/java/com/gentics/contentnode/publish/mesh/MeshPublisher.java
cms-core/src/test/java/com/gentics/contentnode/testutils/mesh/MeshContext.java
cms-oss-changelog/src/changelog/entries/2024/09/7964.SUP-17446.bugfix
cms-oss-changelog/src/changelog/entries/2024/09/7965.SUP-17446.bugfix
pom.xml

Fix possible NPE when tagging new created branch in Mesh CR

Update Mesh Rest Client

---

cms-oss-changelog/src/changelog/entries/2024/10/8008.SUP-17588.bugfix
cms-ui/apps/editor-ui/src/app/shared/components/item-list-row/item-list-row.component.translation.spec.ts
cms-ui/apps/editor-ui/src/app/shared/components/item-list-row/item-list-row.component.ts

Issue: https://jira-gentics.atlassian.net/browse/SUP-17588

SUP-17588: Cannot Create Page Languages

---

cms-core/src/main/resources/com/gentics/contentnode/object/search/file_mapping.json
cms-core/src/main/resources/com/gentics/contentnode/object/search/folder_mapping.json
cms-core/src/main/resources/com/gentics/contentnode/object/search/form_mapping.json
cms-core/src/main/resources/com/gentics/contentnode/object/search/image_mapping.json
cms-core/src/main/resources/com/gentics/contentnode/object/search/page_mapping.json
cms-ui/apps/editor-ui/src/app/list-view/components/item-list/item-list.component.ts
cms-ui/apps/editor-ui/src/app/shared/components/item-list-row/item-list-row.component.html
cms-ui/apps/editor-ui/src/app/state/providers/folder-actions/folder-actions.service.ts
cms-ui/libs/cms-models/src/lib/models/response.ts
cms-ui/libs/cms-rest-clients-angular/src/lib/folder/folder-api.ts

https://jira-gentics.atlassian.net/browse/GPU-1608

GPU-1608 Adapt object mappings for ES 8 update

---

cms-oss-changelog/src/changelog/entries/2024/10/8035.SUP-17507.bugfix
cms-ui/apps/admin-ui/src/app/features/mesh-browser/components/mesh-browser-editor/mesh-browser-editor.component.ts

Issue: https://jira-gentics.atlassian.net/browse/SUP-17507

SUP-17507: Fix displaying folder properties in MeshBrowser

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/SchedulerFactory.java
cms-core/src/main/java/com/gentics/contentnode/init/MigrateScheduler.java
cms-oss-changelog/src/changelog/entries/2024/10/8005.SUP-17559.bugfix

https://jira-gentics.atlassian.net/browse/SUP-17559

SUP-17559 Fix handling of follow up schedules

---

cms-oss-changelog/src/changelog/entries/2024/10/8044.SUP-17665.bugfix
cms-ui/apps/editor-ui/src/app/content-frame/components/content-frame/content-frame.component.spec.ts
cms-ui/apps/editor-ui/src/app/content-frame/components/content-frame/content-frame.component.ts

https://jira-gentics.atlassian.net/browse/SUP-17665

SUP-17665: Re-add fix for cancelling edit view

---

cms-core/src/main/java/com/gentics/contentnode/publish/InstantPublisher.java

node with contentfile auto offline enabled.

SUP 17698: Fix instant publishing of objects referencing files cross

---

cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/AdminResourceImpl.java
cms-core/src/test/java/com/gentics/contentnode/tests/rest/admin/AdminResourceFeatureManagementTest.java

WIP: AdminResource: Feature manipulation

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/TableVersion.java
cms-core/src/test/java/com/gentics/contentnode/tests/versioning/AbstractVersioningTest.java
cms-oss-changelog/src/changelog/entries/2024/12/8078.SUP-17766.bugfix

https://jira-gentics.atlassian.net/browse/SUP-17766

SUP-17766 Fix queries in object/TableVersion for MariaDB 10.4 and later

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/FolderFactory.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/FolderResourceImpl.java

https://jira-gentics.atlassian.net/browse/SUP-17870

SUP-17870 Fix stack overflow error when listing nodes

---

cms-oss-doc/src/main/source/ui_custom_editor.textile

Docs for the syntax highlighter since i searched forever to find it
https://github.com/syntaxhighlighter/SyntaxHighlighter-Site/blob/master/content/SyntaxHighlighter/manual/configuration/index.txt

Fixed formatting of custom-editor docs

---

cms-ui/libs/cms-components/src/lib/core/providers/keycloak/keycloak.service.ts
cms-ui/package-lock.json
cms-ui/package.json

Remove loading of javascript adapter from server

Update NPM dependency keycloak-js to 25.0.5

---

cms-ui/apps/admin-ui/src/app/mesh/components/copy-token-modal/copy-token-modal.component.html
cms-ui/apps/admin-ui/src/app/mesh/components/copy-value/copy-value.component.html
cms-ui/apps/admin-ui/src/app/mesh/components/copy-value/copy-value.component.ts

Not sure if this has to be added to the changelog, giving its "solution"...

SUP-18084: Less secure Mesh token clipboard copy

---

cms-core/src/main/java/com/gentics/contentnode/publish/protocol/PublishProtocolUtil.java

Do not remove "publisher" and "pdate" from page when page is taken

---

cms-core/src/main/java/com/gentics/contentnode/factory/object/SystemUserFactory.java
cms-core/src/main/java/com/gentics/contentnode/object/AbstractSystemUser.java
cms-core/src/main/java/com/gentics/contentnode/object/SystemUser.java
cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/UserResourceImpl.java
cms-core/src/main/resources/changelog/system.CHANGELOG
cms-core/src/main/resources/contentnode_de_DE.properties
cms-core/src/main/resources/contentnode_en_EN.properties
cms-core/src/main/resources/contentnode_fr.properties
cms-core/src/main/resources/contentnode_it.properties
cms-core/src/test/java/com/gentics/contentnode/tests/rest/user/UserResourceTest.java

Revert "GPU-1877 Support user login"

---

cms-oss-changelog/src/changelog/entries/2025/05/8257.SUP-18495.bugfix
cms-ui/apps/admin-ui/src/app/features/scheduler/components/schedule-execution-detail-modal/schedule-execution-detail-modal.component.html
cms-ui/apps/admin-ui/src/app/features/scheduler/components/schedule-executions-table/schedule-executions-table.component.html
cms-ui/apps/admin-ui/src/app/features/scheduler/components/schedule-table/schedule-table.component.html
cms-ui/apps/admin-ui/src/app/shared/components/base-entity-table/base-entity-table.component.scss
cms-ui/apps/admin-ui/src/app/shared/pipes/i18n-duration/i18n-duration.pipe.ts
cms-ui/apps/admin-ui/src/app/shared/pipes/index.ts
cms-ui/apps/admin-ui/src/app/shared/shared.module.ts

SUP-18495: Added i18n-duration pipe; Fixed duration formatting; Fixed… 

---

cms-oss-changelog/src/changelog/entries/2025/08/8364.SUP-18802.bugfix
cms-ui/apps/editor-ui/src/app/content-frame/components/combined-properties-editor/combined-properties-editor.component.ts
cms-ui/apps/editor-ui/src/app/content-frame/components/content-frame/content-frame.component.ts

Change save notification for pages and forms to contain

---

cms-oss-changelog/src/changelog/entries/2025/09/8426.SUP-18856.bugfix
cms-ui/libs/cms-components/src/lib/core/components/rich-content-editor/rich-content-editor.component.cy.ts
cms-ui/libs/cms-components/src/lib/core/components/rich-content-editor/rich-content-editor.component.html
cms-ui/libs/cms-components/src/lib/core/components/rich-content-editor/rich-content-editor.component.ts

I'll also need an assistance on adding a Cypress test on this case :(

SUP-18856: Listen to the content changes in the rich content editor
